services:
  db:
    image: postgres:16
    container_name: wataerp-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssworD
      POSTGRES_DB: wataerp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  db_data:
