name: CI

on:
  push:
    branches: ["main", "master", "develop", "feature/**", "fix/**", "test/**"]
  pull_request:
    branches: ["main", "master", "develop"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      SPRING_PROFILES_ACTIVE: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Build & Test
        run: |
          ./gradlew --version
          ./gradlew clean test jacocoTestReport --no-daemon

      - name: Upload JUnit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: build/reports/tests/test

      - name: Upload JaCoCo coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html
